# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Too Many Notes!
email: jf@collaboration-planners.com
description: > # this means to ignore newlines until "baseurl:"
  Programming notes by a humble programmer standing on the shoulders of giants.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://jfcloutier.github.io" # the base hostname & protocol for your site
twitter_username: jfcloutier
github_username:  jfcloutier

# Build settings
markdown: kramdown
